import { z } from 'zod';
import '@/lib/github/globals';
import { githubFetch } from '@/lib/github/client';
import { getHeadSha, createBranch, commitMultipleFiles, createPR, ensureLabel, addLabelToPR } from '@/lib/github/operations';
import type { PipelineConfig } from '@/lib/agents/pipeline-generator';
import type { CloudInfraConfig } from '@/lib/agents/cloud-infra-generator';
import { remediateCalm } from '@/lib/agents/calm-remediator';
import { applyChangesToCalm } from '@/lib/agents/remediation-merge';

// Prevent Next.js from caching this route
export const dynamic = 'force-dynamic';

// Enable Vercel Fluid Compute 300-second timeout for long-running agent calls
export const maxDuration = 300;

/**
 * Request body schema for PR creation
 */
/**
 * Label configuration for each PR type.
 * Colors are hex without '#'. Values chosen for GitHub's standard palette.
 */
const LABEL_MAP: Record<string, { name: string; color: string; description: string }> = {
  pipeline: { name: 'ci/cd', color: '0075ca', description: 'CI/CD pipeline changes' },
  remediation: { name: 'compliance', color: 'e4e669', description: 'Compliance remediation' },
  infra: { name: 'infrastructure', color: '0052cc', description: 'Infrastructure changes' },
};

const createPRRequestSchema = z.object({
  type: z.enum(['pipeline', 'remediation', 'infra']),
  owner: z.string(),
  repo: z.string(),
  filePath: z.string(),       // original CALM file path (for remediation)
  fileSha: z.string(),        // current SHA of CALM file (for remediation)
  defaultBranch: z.string(),  // base branch for PR
});

/**
 * Map GitHub HTTP status codes to descriptive user-facing messages.
 */
function mapGitHubError(statusCode: number, raw: string): string {
  if (statusCode === 401 || statusCode === 403) {
    return 'Authentication failed. Check GITHUB_TOKEN permissions (needs "repo" scope).';
  }
  if (statusCode === 404) {
    return 'Repository or branch not found.';
  }
  if (statusCode === 422) {
    return 'GitHub rejected the request — branch may already exist or permissions insufficient.';
  }
  return `GitHub API error (${statusCode}): ${raw}`;
}

/**
 * Build pipeline files array from a PipelineConfig result.
 *
 * Files committed to the DevSecOps CI PR:
 *   .github/workflows/calmguard-ci.yml     — main CI/CD workflow
 *   .github/{tool.name}.yml               — security scanning tool configs
 *
 * IaC REMOVED — now lives in Cloud Infrastructure PR only (GOPS-02).
 */
function buildPipelineFiles(
  pipeline: PipelineConfig,
): Array<{ path: string; content: string }> {
  const files: Array<{ path: string; content: string }> = [];

  // Main GitHub Actions workflow
  files.push({
    path: '.github/workflows/calmguard-ci.yml',
    content: pipeline.githubActions.yaml,
  });

  // Security scanning tool configs
  for (const tool of pipeline.securityScanning.tools) {
    files.push({
      path: `.github/${tool.name}.yml`,
      content: tool.config,
    });
  }

  // IaC REMOVED — now lives in Cloud Infrastructure PR only (GOPS-02)
  return files;
}

/**
 * Build Terraform files array from a CloudInfraConfig result.
 *
 * Files committed to the Cloud Infrastructure PR:
 *   terraform/*.tf — one module per logical grouping
 */
function buildInfraFiles(
  infra: CloudInfraConfig,
): Array<{ path: string; content: string }> {
  return infra.terraform.modules.map((mod) => ({
    path: mod.filename,
    content: mod.content,
  }));
}

/**
 * Build the PR body Markdown for a Cloud Infrastructure PR.
 * Includes CALM traceability section linking each Terraform resource to its CALM element.
 */
function buildInfraPRBody(infra: CloudInfraConfig): string {
  const traceabilityList = infra.traceability
    .map((t) => `- **${t.calmElement}** → \`${t.generatedResource}\`: ${t.rationale}`)
    .join('\n');

  const moduleList = infra.terraform.modules
    .map((m) => `- \`${m.filename}\` — ${m.calmSignal}`)
    .join('\n');

  return [
    '## CALMGuard Cloud Infrastructure',
    '',
    'Generated by [CALMGuard](https://github.com/finos-labs/dtcch-2026-opsflow-llc) compliance analysis.',
    '',
    '### Summary',
    infra.summary,
    '',
    '### Terraform Modules',
    moduleList,
    '',
    '### CALM Traceability',
    '',
    traceabilityList,
    '',
    '---',
    '*Generated by CALMGuard CALM-native compliance platform*',
  ].join('\n');
}

/**
 * Build the PR body Markdown for a DevSecOps CI pipeline PR.
 * Covers only GitHub Actions workflow and security scanning configs (no IaC).
 */
function buildPipelinePRBody(
  pipeline: PipelineConfig,
  files: Array<{ path: string; content: string }>,
): string {
  const fileList = files
    .map((f) => {
      if (f.path === '.github/workflows/calmguard-ci.yml') {
        return `- \`${f.path}\` — CI/CD workflow with build, test, security scan, deploy stages`;
      }
      const tool = pipeline.securityScanning.tools.find(
        (t) => `.github/${t.name}.yml` === f.path,
      );
      if (tool) {
        return `- \`${f.path}\` — ${tool.description}`;
      }
      return `- \`${f.path}\``;
    })
    .join('\n');

  const toolList = pipeline.securityScanning.tools
    .map((t) => `- **${t.name}**: ${t.description}`)
    .join('\n');

  const recList = pipeline.recommendations
    .map((r) => `- [${r.priority}] ${r.category}: ${r.recommendation}`)
    .join('\n');

  return [
    '## CALMGuard Pipeline Artifacts',
    '',
    'Generated by [CALMGuard](https://github.com/finos-labs/dtcch-2026-opsflow-llc) compliance analysis.',
    '',
    '### Summary',
    pipeline.summary,
    '',
    '### Files Added',
    fileList,
    '',
    '### Security Scanning Tools',
    toolList,
    '',
    '### Recommendations',
    recList,
    '',
    '---',
    '*Generated by CALMGuard CALM-native compliance platform*',
  ].join('\n');
}

/**
 * POST /api/github/create-pr
 *
 * Creates a GitHub PR with generated pipeline artifacts or compliance remediation.
 * Streams SSE progress events during the process.
 *
 * Request body: CreatePRRequest
 * Response: text/event-stream — sequence of SSE frames:
 *   data: { type: "step", step: string }\n\n
 *   data: { type: "done", prUrl, prNumber, branchName, fileCount }\n\n
 *   data: { type: "error", message: string }\n\n
 */
export async function POST(req: Request): Promise<Response> {
  // 1. Validate request body
  let bodyRaw: unknown;
  try {
    bodyRaw = await req.json();
  } catch {
    return Response.json({ error: 'Invalid JSON in request body' }, { status: 400 });
  }

  const bodyResult = createPRRequestSchema.safeParse(bodyRaw);
  if (!bodyResult.success) {
    return Response.json(
      { error: 'Invalid request body', issues: bodyResult.error.issues },
      { status: 400 },
    );
  }

  const { type, owner, repo, filePath, fileSha, defaultBranch } = bodyResult.data;

  // 2. Require GITHUB_TOKEN for write operations
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    return Response.json(
      {
        error: 'GITHUB_TOKEN is not configured. Set it in your environment to enable PR generation.',
      },
      { status: 503 },
    );
  }

  // 3. Stream PR creation steps as SSE
  const encoder = new TextEncoder();

  const stream = new ReadableStream({
    async start(controller) {
      const emit = (data: unknown) => {
        controller.enqueue(encoder.encode(`data: ${JSON.stringify(data)}\n\n`));
      };

      try {
        if (type === 'pipeline') {
          // ----------------------------------------------------------------
          // Pipeline PR: multi-file commit (GitHub Actions, SAST, IaC)
          // ----------------------------------------------------------------

          // Step 1: Get HEAD SHA
          emit({ type: 'step', step: 'Getting HEAD SHA...' });
          const headSha = await getHeadSha(owner, repo, defaultBranch, token).catch((err: unknown) => {
            const msg = err instanceof Error ? err.message : String(err);
            if (msg.includes('(401)') || msg.includes('(403)')) {
              throw new Error(mapGitHubError(403, msg));
            }
            if (msg.includes('(404)')) {
              throw new Error(mapGitHubError(404, msg));
            }
            throw new Error(msg);
          });

          // Step 2: Create branch
          const pipelineBranchName = `calmguard/devsecops-ci-${Date.now()}`;
          emit({ type: 'step', step: 'Creating branch...' });
          await createBranch(owner, repo, pipelineBranchName, headSha, token).catch((err: unknown) => {
            const msg = err instanceof Error ? err.message : String(err);
            if (msg.includes('(422)')) {
              throw new Error(mapGitHubError(422, msg));
            }
            throw new Error(msg);
          });

          // Step 3: Commit pipeline artifacts (CI workflow + security configs only, no IaC)
          emit({ type: 'step', step: 'Committing pipeline artifacts...' });

          const pipeline = globalThis.__lastPipelineResult;
          if (!pipeline) {
            throw new Error(
              'Pipeline analysis results not available. Run analysis first.',
            );
          }

          const files = buildPipelineFiles(pipeline);
          await commitMultipleFiles(
            owner,
            repo,
            pipelineBranchName,
            files,
            'chore: add CALMGuard DevSecOps CI pipeline artifacts',
            headSha,
            token,
          );

          // Step 4: Open pull request
          emit({ type: 'step', step: 'Opening pull request...' });
          const prBody = buildPipelinePRBody(pipeline, files);
          const { html_url: pipelinePrUrl, number: pipelinePrNumber } = await createPR(
            owner,
            repo,
            pipelineBranchName,
            defaultBranch,
            'chore: add CALMGuard DevSecOps CI pipeline',
            prBody,
            token,
          );

          // Step 5: Auto-label
          const pipelineLabel = LABEL_MAP['pipeline'];
          await ensureLabel(owner, repo, pipelineLabel.name, pipelineLabel.color, pipelineLabel.description, token);
          await addLabelToPR(owner, repo, pipelinePrNumber, [pipelineLabel.name], token);

          // Emit done — client uses this to update PR card state
          emit({
            type: 'done',
            prUrl: pipelinePrUrl,
            prNumber: pipelinePrNumber,
            branchName: pipelineBranchName,
            fileCount: files.length,
            filePath,
            fileSha,
          });
        } else if (type === 'remediation') {
          // ----------------------------------------------------------------
          // Remediation PR: single-file commit via Contents API (PUT)
          // ----------------------------------------------------------------

          // Step 1: Run CALM remediation agent
          emit({ type: 'step', step: 'Running CALM remediation agent...' });

          const analysisResult = globalThis.__lastAnalysisResult;
          const calmDocument = globalThis.__lastCalmDocument;

          if (!analysisResult || !calmDocument) {
            throw new Error('Analysis results not available. Run analysis first.');
          }

          const { compliance, risk } = analysisResult;
          if (!compliance || !risk) {
            throw new Error('Compliance or risk analysis failed. Cannot remediate.');
          }

          const remediationResult = await remediateCalm(calmDocument, compliance, risk);
          if (!remediationResult.success || !remediationResult.data) {
            throw new Error(remediationResult.error ?? 'Remediation agent failed with unknown error.');
          }

          const { changes, summary } = remediationResult.data;

          // Apply changes programmatically — LLMs identify gaps accurately in
          // the changes[] array but fail to embed 30+ controls into the JSON document.
          // We use the structured changes as deterministic patch instructions.
          const remediatedCalm = applyChangesToCalm(calmDocument, changes);

          // Step 2: Get HEAD SHA
          emit({ type: 'step', step: 'Getting HEAD SHA...' });
          const headSha = await getHeadSha(owner, repo, defaultBranch, token).catch((err: unknown) => {
            const msg = err instanceof Error ? err.message : String(err);
            if (msg.includes('(401)') || msg.includes('(403)')) {
              throw new Error(mapGitHubError(403, msg));
            }
            if (msg.includes('(404)')) {
              throw new Error(mapGitHubError(404, msg));
            }
            throw new Error(msg);
          });

          // Step 3: Create branch
          const remediationBranchName = `calmguard/compliance-remediation-${Date.now()}`;
          emit({ type: 'step', step: 'Creating branch...' });
          await createBranch(owner, repo, remediationBranchName, headSha, token).catch((err: unknown) => {
            const msg = err instanceof Error ? err.message : String(err);
            if (msg.includes('(422)')) {
              throw new Error(mapGitHubError(422, msg));
            }
            throw new Error(msg);
          });

          // Step 4: Commit remediated CALM file via GitHub Contents API (PUT)
          // Using PUT /repos/{owner}/{repo}/contents/{path} for single-file commit
          emit({ type: 'step', step: 'Committing remediated CALM file...' });

          const remediatedContent = Buffer.from(
            JSON.stringify(remediatedCalm, null, 2),
          ).toString('base64');

          const contentResponse = await githubFetch(
            `/repos/${owner}/${repo}/contents/${filePath}`,
            {
              method: 'PUT',
              token,
              body: JSON.stringify({
                message: 'fix: apply CALMGuard compliance remediation',
                content: remediatedContent,
                branch: remediationBranchName,
                sha: fileSha, // CRITICAL: required because file already exists
              }),
            },
          );

          if (!contentResponse.ok) {
            const errorText = await contentResponse.text();
            throw new Error(mapGitHubError(contentResponse.status, errorText));
          }

          // Step 5: Open pull request with per-change explanations
          emit({ type: 'step', step: 'Opening pull request...' });

          const protocolUpgradeCount = changes.filter((c) => c.changeType === 'protocol-upgrade').length;
          const controlAddedCount = changes.filter((c) => c.changeType === 'control-added').length;

          const changesList = changes
            .map(
              (change, i) =>
                [
                  `#### ${i + 1}. ${change.description}`,
                  `- **Type:** ${change.changeType === 'protocol-upgrade' ? 'Protocol Upgrade' : 'Control Added'}`,
                  `- **Element:** \`${change.nodeOrRelationshipId}\``,
                  `- **Before:** ${change.before}`,
                  `- **After:** ${change.after}`,
                  `- **Rationale:** ${change.rationale}`,
                ].join('\n')
            )
            .join('\n\n');

          const remediationPrBody = [
            '## CALMGuard Compliance Remediation',
            '',
            'Generated by [CALMGuard](https://github.com/finos-labs/dtcch-2026-opsflow-llc) compliance analysis.',
            '',
            '### Summary',
            summary,
            '',
            '### Changes Made',
            '',
            changesList,
            '',
            '---',
            '',
            '### Remediation Statistics',
            `- Total changes: ${changes.length}`,
            `- Protocol upgrades: ${protocolUpgradeCount}`,
            `- Controls added: ${controlAddedCount}`,
            '',
            '---',
            '*Generated by CALMGuard CALM-native compliance platform*',
          ].join('\n');

          const { html_url: remediationPrUrl, number: remediationPrNumber } = await createPR(
            owner,
            repo,
            remediationBranchName,
            defaultBranch,
            'fix: apply CALMGuard compliance remediation',
            remediationPrBody,
            token,
          );

          // Auto-label
          const remediationLabel = LABEL_MAP['remediation'];
          await ensureLabel(owner, repo, remediationLabel.name, remediationLabel.color, remediationLabel.description, token);
          await addLabelToPR(owner, repo, remediationPrNumber, [remediationLabel.name], token);

          emit({
            type: 'done',
            prUrl: remediationPrUrl,
            prNumber: remediationPrNumber,
            branchName: remediationBranchName,
            fileCount: 1,
          });
        } else if (type === 'infra') {
          // ----------------------------------------------------------------
          // Cloud Infrastructure PR: multi-file commit (Terraform modules)
          // ----------------------------------------------------------------

          // Step 1: Get HEAD SHA
          emit({ type: 'step', step: 'Getting HEAD SHA...' });
          const headSha = await getHeadSha(owner, repo, defaultBranch, token).catch((err: unknown) => {
            const msg = err instanceof Error ? err.message : String(err);
            if (msg.includes('(401)') || msg.includes('(403)')) {
              throw new Error(mapGitHubError(403, msg));
            }
            if (msg.includes('(404)')) {
              throw new Error(mapGitHubError(404, msg));
            }
            throw new Error(msg);
          });

          // Step 2: Create branch
          const infraBranchName = `calmguard/cloud-infra-${Date.now()}`;
          emit({ type: 'step', step: 'Creating branch...' });
          await createBranch(owner, repo, infraBranchName, headSha, token).catch((err: unknown) => {
            const msg = err instanceof Error ? err.message : String(err);
            if (msg.includes('(422)')) {
              throw new Error(mapGitHubError(422, msg));
            }
            throw new Error(msg);
          });

          // Step 3: Commit Terraform modules
          emit({ type: 'step', step: 'Committing infrastructure modules...' });

          const infra = globalThis.__lastCloudInfraResult;
          if (!infra) {
            throw new Error(
              'Cloud infrastructure analysis not available. Run analysis first.',
            );
          }

          const infraFiles = buildInfraFiles(infra);
          await commitMultipleFiles(
            owner,
            repo,
            infraBranchName,
            infraFiles,
            'chore: add CALMGuard cloud infrastructure scaffolds',
            headSha,
            token,
          );

          // Step 4: Open pull request
          emit({ type: 'step', step: 'Opening pull request...' });
          const infraPRBody = buildInfraPRBody(infra);
          const { html_url: infraPrUrl, number: infraPrNumber } = await createPR(
            owner,
            repo,
            infraBranchName,
            defaultBranch,
            'chore: add CALMGuard cloud infrastructure',
            infraPRBody,
            token,
          );

          // Step 5: Auto-label
          const infraLabel = LABEL_MAP['infra'];
          await ensureLabel(owner, repo, infraLabel.name, infraLabel.color, infraLabel.description, token);
          await addLabelToPR(owner, repo, infraPrNumber, [infraLabel.name], token);

          emit({
            type: 'done',
            prUrl: infraPrUrl,
            prNumber: infraPrNumber,
            branchName: infraBranchName,
            fileCount: infraFiles.length,
          });
        }
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        emit({ type: 'error', message });
      } finally {
        controller.close();
      }
    },
  });

  return new Response(stream, {
    headers: {
      'Content-Type': 'text/event-stream; charset=utf-8',
      'Cache-Control': 'no-cache, no-transform',
      'Connection': 'keep-alive',
    },
  });
}
