apiVersion: apps/v1
kind: Deployment
metadata:
  name: trades
  labels:
    app: trades
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trades
  template:
    metadata:
      labels:
        app: trades
    spec:
      containers:
        - name: trades
          image: {{ trades-api-image }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ trades-api-port }}
          readinessProbe:
            httpGet:
              path: /trades
              port: {{ trades-api-port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /trades
              port: {{ trades-api-port }}
            initialDelaySeconds: 10
            periodSeconds: 30
