apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: conference

resources:
  - namespace.yaml
  - application-deployment.yaml
  - application-service.yaml
  - database-deployment.yaml
  - database-service.yaml