/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
    "title": "My Docusaurus Docs",
    "tagline": "Generated documentation from CALM",
    "url": "http://localhost",
    "baseUrl": "/",
    "onBrokenLinks": "throw",
    "onBrokenMarkdownLinks": "warn",
    "favicon": "img/favicon.ico",
    "organizationName": "my-org",
    "projectName": "calm-docs",
    "themeConfig": {
        "navbar": {
            "title": "CALM Documentation",
            "logo": {
                "alt": "Calm Logo",
                "src": "img/2025_CALM_Icon.svg"
            },
            "hideOnScroll": false,
            "items": []
        },
        "colorMode": {
            "defaultMode": "light",
            "disableSwitch": false,
            "respectPrefersColorScheme": false
        },
        "docs": {
            "versionPersistence": "localStorage",
            "sidebar": {
                "hideable": false,
                "autoCollapseCategories": false
            }
        },
        "blog": {
            "sidebar": {
                "groupByYear": true
            }
        },
        "metadata": [],
        "prism": {
            "additionalLanguages": [],
            "theme": {
                "plain": {
                    "color": "#bfc7d5",
                    "backgroundColor": "#292d3e"
                },
                "styles": [
                    {
                        "types": [
                            "comment"
                        ],
                        "style": {
                            "color": "rgb(105, 112, 152)",
                            "fontStyle": "italic"
                        }
                    },
                    {
                        "types": [
                            "string",
                            "inserted"
                        ],
                        "style": {
                            "color": "rgb(195, 232, 141)"
                        }
                    },
                    {
                        "types": [
                            "number"
                        ],
                        "style": {
                            "color": "rgb(247, 140, 108)"
                        }
                    },
                    {
                        "types": [
                            "builtin",
                            "char",
                            "constant",
                            "function"
                        ],
                        "style": {
                            "color": "rgb(130, 170, 255)"
                        }
                    },
                    {
                        "types": [
                            "punctuation",
                            "selector"
                        ],
                        "style": {
                            "color": "rgb(199, 146, 234)"
                        }
                    },
                    {
                        "types": [
                            "variable"
                        ],
                        "style": {
                            "color": "rgb(191, 199, 213)"
                        }
                    },
                    {
                        "types": [
                            "class-name",
                            "attr-name"
                        ],
                        "style": {
                            "color": "rgb(255, 203, 107)"
                        }
                    },
                    {
                        "types": [
                            "tag",
                            "deleted"
                        ],
                        "style": {
                            "color": "rgb(255, 85, 114)"
                        }
                    },
                    {
                        "types": [
                            "operator"
                        ],
                        "style": {
                            "color": "rgb(137, 221, 255)"
                        }
                    },
                    {
                        "types": [
                            "boolean"
                        ],
                        "style": {
                            "color": "rgb(255, 88, 116)"
                        }
                    },
                    {
                        "types": [
                            "keyword"
                        ],
                        "style": {
                            "fontStyle": "italic"
                        }
                    },
                    {
                        "types": [
                            "doctype"
                        ],
                        "style": {
                            "color": "rgb(199, 146, 234)",
                            "fontStyle": "italic"
                        }
                    },
                    {
                        "types": [
                            "namespace"
                        ],
                        "style": {
                            "color": "rgb(178, 204, 214)"
                        }
                    },
                    {
                        "types": [
                            "url"
                        ],
                        "style": {
                            "color": "rgb(221, 221, 221)"
                        }
                    }
                ]
            },
            "magicComments": [
                {
                    "className": "theme-code-block-highlighted-line",
                    "line": "highlight-next-line",
                    "block": {
                        "start": "highlight-start",
                        "end": "highlight-end"
                    }
                }
            ]
        },
        "tableOfContents": {
            "minHeadingLevel": 2,
            "maxHeadingLevel": 3
        },
        "mermaid": {
            "theme": {
                "dark": "dark",
                "light": "default"
            },
            "options": {}
        }
    },
    "themes": [
        "@docusaurus/theme-mermaid"
    ],
    "markdown": {
        "mermaid": true,
        "format": "mdx",
        "mdx1Compat": {
            "comments": true,
            "admonitions": true,
            "headingIds": true
        },
        "anchors": {
            "maintainCase": false
        }
    },
    "stylesheets": [
        "/css/custom.css"
    ],
    "presets": [
        [
            "classic",
            {
                "docs": {
                    "sidebarPath": "/Users/matthewbain/Development/github/architecture-as-code/calm/getting-started/website/sidebars.js",
                    "routeBasePath": "/",
                    "remarkPlugins": [
                        null
                    ]
                }
            }
        ]
    ],
    "plugins": [
        [
            "/Users/matthewbain/Development/github/architecture-as-code/node_modules/docusaurus-plugin-search-local/lib/server/index.js",
            {
                "indexDocs": true,
                "indexPages": true,
                "highlightSearchTermsOnTargetPage": true,
                "removeDefaultStopWordFilter": true
            }
        ]
    ],
    "baseUrlIssueBanner": true,
    "i18n": {
        "defaultLocale": "en",
        "path": "i18n",
        "locales": [
            "en"
        ],
        "localeConfigs": {}
    },
    "future": {
        "v4": {
            "removeLegacyPostBuildHeadAttribute": false,
            "useCssCascadeLayers": false
        },
        "experimental_faster": {
            "swcJsLoader": false,
            "swcJsMinimizer": false,
            "swcHtmlMinimizer": false,
            "lightningCssMinimizer": false,
            "mdxCrossCompilerCache": false,
            "rspackBundler": false,
            "rspackPersistentCache": false,
            "ssgWorkerThreads": false
        },
        "experimental_storage": {
            "type": "localStorage",
            "namespace": false
        },
        "experimental_router": "browser"
    },
    "onBrokenAnchors": "warn",
    "onDuplicateRoutes": "warn",
    "staticDirectories": [
        "static"
    ],
    "customFields": {},
    "scripts": [],
    "headTags": [],
    "clientModules": [],
    "titleDelimiter": "|",
    "noIndex": false
};
