apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - trades-deployment.yaml
  - trades-service.yaml
  - mcp-deployment.yaml
  - mcp-service.yaml
  - a2a-deployment.yaml
  - a2a-service.yaml
  - denied-symbols-configmap.yaml
  - network-policies.yaml
