apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendees
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendees
  template:
    metadata:
      labels:
        app: attendees
    spec:
      containers:
        - name: app
          image: https://example.com/images/attendees-service:latest
          ports:
            - containerPort: 9000