apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-db-from-app
spec:
  podSelector:
    matchLabels:
      db: attendees-store
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: attendees
  policyTypes:
    - Ingress