// SPDX-FileCopyrightText: 2024 CalmStudio contributors - see NOTICE file
//
// SPDX-License-Identifier: Apache-2.0

import { Buffer } from 'node:buffer';
import type { getOctokit } from '@actions/github';
import type { context as GitHubContext } from '@actions/github';
import type { RenderResult } from './render.js';

type Octokit = ReturnType<typeof getOctokit>;
type Context = typeof GitHubContext;

/**
 * Hidden marker used to identify the CalmStudio PR comment for upsert.
 * Must be exactly this string — tested in action.test.ts.
 */
export const MARKER = '<!-- calmstudio-diagram-comment -->';

/**
 * Commit each SVG to the gh-diagrams branch and return a raw.githubusercontent.com URL.
 * Creates the branch if it doesn't exist (uses the default branch as base).
 */
async function commitSvgToBranch(
  octokit: Octokit,
  context: Context,
  fileName: string,
  svg: string
): Promise<string> {
  const { owner, repo } = context.repo;
  const branch = 'gh-diagrams';
  const path = `diagrams/${fileName}.svg`;
  const content = Buffer.from(svg, 'utf-8').toString('base64');

  // Try to get the current file SHA (for update vs create)
  let sha: string | undefined;
  try {
    const existing = await octokit.rest.repos.getContent({
      owner,
      repo,
      path,
      ref: branch
    });
    // getContent returns array for directories; we have a file
    if (!Array.isArray(existing.data) && 'sha' in existing.data) {
      sha = existing.data.sha;
    }
  } catch {
    // File doesn't exist yet — proceed with create
  }

  await octokit.rest.repos.createOrUpdateFileContents({
    owner,
    repo,
    path,
    message: `chore(diagrams): update ${fileName}`,
    content,
    branch,
    ...(sha ? { sha } : {})
  });

  return `https://raw.githubusercontent.com/${owner}/${repo}/${branch}/${path}`;
}

/**
 * Build the PR comment body from render results.
 * Each SVG is committed to the gh-diagrams branch and referenced via a raw URL.
 */
export async function buildCommentBody(
  renders: RenderResult[],
  octokit: Octokit,
  context: Context
): Promise<string> {
  const sections: string[] = [
    MARKER,
    '## CALM Architecture Diagrams',
    ''
  ];

  for (const render of renders) {
    sections.push(`### ${render.fileName}`, '');

    // Commit SVG and get URL
    let imgLine: string;
    try {
      const imgUrl = await commitSvgToBranch(octokit, context, render.fileName, render.svg);
      imgLine = `<img src="${imgUrl}" alt="${render.fileName}" />`;
    } catch {
      // Fallback: embed as base64 data URI (GitHub won't render it, but keeps the body informative)
      const b64 = Buffer.from(render.svg, 'utf-8').toString('base64');
      imgLine = `<img src="data:image/svg+xml;base64,${b64}" alt="${render.fileName}" />`;
    }

    sections.push(imgLine, '');

    // Validation summary
    const errors = render.issues.filter((i) => i.severity === 'error');
    const warnings = render.issues.filter((i) => i.severity === 'warning');

    if (render.issues.length === 0) {
      sections.push('**Validation:** No issues found.', '');
    } else {
      sections.push(
        `**Validation:** ${errors.length} error(s), ${warnings.length} warning(s)`,
        ''
      );
      for (const issue of render.issues) {
        const icon = issue.severity === 'error' ? 'error' : 'warning';
        sections.push(`- **${icon}:** ${issue.message}`);
      }
      sections.push('');
    }
  }

  sections.push(
    '---',
    '*Generated by [CalmStudio](https://github.com/finos/architecture-as-code)*'
  );

  return sections.join('\n');
}

/**
 * Create or update the CalmStudio PR comment using the hidden MARKER for idempotency.
 * Returns the URL of the comment.
 */
export async function upsertComment(
  octokit: Octokit,
  context: Context,
  body: string
): Promise<string> {
  const { owner, repo } = context.repo;
  const issueNumber = context.payload.pull_request?.number as number;

  // Find existing comment with our marker
  const existing = await octokit.rest.issues.listComments({
    owner,
    repo,
    issue_number: issueNumber
  });

  const found = existing.data.find(
    (c) => typeof c.body === 'string' && c.body.includes(MARKER)
  );

  if (found) {
    const response = await octokit.rest.issues.updateComment({
      owner,
      repo,
      comment_id: found.id,
      body
    });
    return response.data.html_url;
  }

  const response = await octokit.rest.issues.createComment({
    owner,
    repo,
    issue_number: issueNumber,
    body
  });
  return response.data.html_url;
}
