apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: calm-hub
  namespace: calm-hub
  labels:
    app.kubernetes.io/name: calm-hub
    app.kubernetes.io/part-of: calm
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: calm-hub
      app.kubernetes.io/component: api
