apiVersion: v1
kind: ServiceAccount
metadata:
  name: calm-hub
  namespace: calm-hub
  labels:
    app.kubernetes.io/name: calm-hub
    app.kubernetes.io/part-of: calm
automountServiceAccountToken: false
