Args = --initialize-at-run-time=org.dizitart.no2.collection.NitriteId,\
       org.dizitart.no2.collection.SnowflakeIdGenerator \
       -H:SerializationConfigurationResources=${.}/serialization-config.json
