// SPDX-FileCopyrightText: 2026 CalmStudio Contributors
//
// SPDX-License-Identifier: Apache-2.0

/**
 * export.test.ts — Unit tests for export.ts CALM JSON transformation logic.
 *
 * Tests focus on:
 * - AIGF decorator injection (via exportAsCalm JSON transformation)
 * - _template metadata stripping
 * - Content preservation (nodes, relationships, controls)
 *
 * SVG/PNG export requires a real browser (html-to-image) and is skipped here.
 *
 * Strategy: Mock downloadDataUrl from $lib/io/fileSystem to capture content
 * and URL.createObjectURL/revokeObjectURL to prevent DOM navigation.
 */

import { describe, it, expect, beforeEach, vi, afterEach } from 'vitest';
import { createMinimalArch, createAIGovernanceArch } from '@calmstudio/calm-core/test-fixtures';

// ─── Mock fileSystem module to capture exported content ───────────────────────
// We intercept downloadDataUrl calls and capture the href (blob: URL) value.
// Since we also stub URL, we can recover the blob content from the href.

vi.mock('$lib/io/fileSystem', () => ({
	downloadDataUrl: vi.fn(),
}));

// Mock scalerToml module before importing export
vi.mock('$lib/io/scalerToml', () => ({
	buildScalerToml: vi.fn(() => '# Generated by CalmStudio\n[scheduler]\nscheduler_address = "tcp://127.0.0.1:8516"\n'),
}));

// Import export functions AFTER mocking their dependency
import { exportAsCalm, exportAsScalerToml } from '$lib/io/export';
import { downloadDataUrl } from '$lib/io/fileSystem';
import { buildScalerToml } from '$lib/io/scalerToml';

// ─── Blob text capture helper ─────────────────────────────────────────────────

// Keep a registry of blob URL -> content for our fake Blob/URL
const blobRegistry = new Map<string, string>();
let blobCounter = 0;

function setupBlobStubs() {
	blobCounter = 0;
	blobRegistry.clear();

	// Stub Blob to store content in registry
	vi.stubGlobal(
		'Blob',
		class MockBlob {
			_id: string;
			constructor(parts: BlobPart[], _init?: BlobPropertyBag) {
				blobCounter++;
				this._id = `blob-${blobCounter}`;
				blobRegistry.set(this._id, (parts as string[]).join(''));
			}
		}
	);

	// Stub URL.createObjectURL to return a trackable fake URL
	vi.stubGlobal('URL', {
		createObjectURL: (blob: { _id: string }) => `blob:fake/${blob._id}`,
		revokeObjectURL: vi.fn(),
	});
}

function teardownBlobStubs() {
	vi.restoreAllMocks();
	vi.unstubAllGlobals();
	blobRegistry.clear();
}

/** Get the content of the first Blob created (the main CALM JSON export). */
function getFirstBlobContent(): string | null {
	return blobRegistry.get('blob-1') ?? null;
}

// ─── Setup / teardown ─────────────────────────────────────────────────────────

beforeEach(() => {
	vi.useFakeTimers();
	vi.clearAllMocks();
	setupBlobStubs();
});

afterEach(() => {
	vi.runAllTimers(); // flush all pending setTimeout callbacks before teardown
	vi.useRealTimers();
	teardownBlobStubs();
});

// ─── exportAsCalm — _template metadata stripping ─────────────────────────────

describe('exportAsCalm — template stripping', () => {
	it('strips _template metadata from the output JSON', () => {
		const archWithTemplate = {
			...createMinimalArch(),
			_template: {
				id: 'test-template',
				name: 'Test',
				description: 'A test template',
				category: 'test',
				tags: [],
				version: '1.0',
				author: 'test',
			},
		};
		const json = JSON.stringify(archWithTemplate, null, 2);
		exportAsCalm(json);
		const content = getFirstBlobContent();
		expect(content).not.toBeNull();
		const result = JSON.parse(content!);
		expect(result).not.toHaveProperty('_template');
	});

	it('preserves nodes when _template is stripped', () => {
		const archWithTemplate = {
			...createMinimalArch(),
			_template: { id: 'x', name: 'x', description: '', category: 'x', tags: [], version: '1', author: 'x' },
		};
		exportAsCalm(JSON.stringify(archWithTemplate, null, 2));
		const result = JSON.parse(getFirstBlobContent()!);
		expect(result.nodes).toHaveLength(2); // createMinimalArch has 2 nodes
	});

	it('passes through clean arch without _template unchanged in structure', () => {
		exportAsCalm(JSON.stringify(createMinimalArch(), null, 2));
		const result = JSON.parse(getFirstBlobContent()!);
		expect(result.nodes).toHaveLength(2);
		expect(result.relationships).toHaveLength(1);
	});
});

// ─── exportAsCalm — AIGF decorator injection ──────────────────────────────────

describe('exportAsCalm — AIGF decorator injection', () => {
	it('does NOT add decorators for architecture with no AI nodes', () => {
		exportAsCalm(JSON.stringify(createMinimalArch(), null, 2));
		const result = JSON.parse(getFirstBlobContent()!);
		expect(result.decorators).toBeUndefined();
	});

	it('injects AIGF governance decorator when AI nodes are present', () => {
		exportAsCalm(JSON.stringify(createAIGovernanceArch(), null, 2));
		const result = JSON.parse(getFirstBlobContent()!);
		expect(result.decorators).toBeDefined();
		expect(Array.isArray(result.decorators)).toBe(true);
		expect(result.decorators).toHaveLength(1);
	});

	it('decorator type is "aigf-governance"', () => {
		exportAsCalm(JSON.stringify(createAIGovernanceArch(), null, 2));
		const result = JSON.parse(getFirstBlobContent()!);
		expect(result.decorators[0].type).toBe('aigf-governance');
	});

	it('decorator has unique-id "aigf-governance-overlay"', () => {
		exportAsCalm(JSON.stringify(createAIGovernanceArch(), null, 2));
		const result = JSON.parse(getFirstBlobContent()!);
		expect(result.decorators[0]['unique-id']).toBe('aigf-governance-overlay');
	});

	it('decorator applies-to includes AI node IDs', () => {
		exportAsCalm(JSON.stringify(createAIGovernanceArch(), null, 2));
		const result = JSON.parse(getFirstBlobContent()!);
		const appliesTo: string[] = result.decorators[0]['applies-to'];
		expect(appliesTo).toContain('ai-llm');
		expect(appliesTo).toContain('ai-agent');
		expect(appliesTo).toContain('ai-orchestrator');
	});

	it('decorator data has governance-score between 0 and 100', () => {
		exportAsCalm(JSON.stringify(createAIGovernanceArch(), null, 2));
		const result = JSON.parse(getFirstBlobContent()!);
		const score = result.decorators[0].data['governance-score'];
		expect(typeof score).toBe('number');
		expect(score).toBeGreaterThanOrEqual(0);
		expect(score).toBeLessThanOrEqual(100);
	});

	it('decorator data includes FINOS AIGF framework reference', () => {
		exportAsCalm(JSON.stringify(createAIGovernanceArch(), null, 2));
		const result = JSON.parse(getFirstBlobContent()!);
		expect(result.decorators[0].data.framework).toBe('FINOS AI Governance Framework');
	});
});

// ─── exportAsCalm — content preservation ─────────────────────────────────────

describe('exportAsCalm — CALM field preservation', () => {
	it('preserves all nodes in output', () => {
		const arch = createMinimalArch();
		exportAsCalm(JSON.stringify(arch, null, 2));
		const result = JSON.parse(getFirstBlobContent()!);
		expect(result.nodes).toHaveLength(arch.nodes.length);
		expect(result.nodes[0]['unique-id']).toBe('api-service');
	});

	it('preserves all relationships in output', () => {
		const arch = createMinimalArch();
		exportAsCalm(JSON.stringify(arch, null, 2));
		const result = JSON.parse(getFirstBlobContent()!);
		expect(result.relationships).toHaveLength(arch.relationships.length);
		expect(result.relationships[0]['unique-id']).toBe('api-to-db');
	});

	it('preserves node controls in AI arch output', () => {
		exportAsCalm(JSON.stringify(createAIGovernanceArch(), null, 2));
		const result = JSON.parse(getFirstBlobContent()!);
		const llmNode = result.nodes.find((n: { 'unique-id': string }) => n['unique-id'] === 'ai-llm');
		expect(llmNode).toBeDefined();
		expect(llmNode.controls['security-domain']).toBeDefined();
	});

	it('outputs original content for malformed input (graceful fallback)', () => {
		const badInput = 'not-valid-json';
		exportAsCalm(badInput);
		// With invalid JSON, falls through to Blob with original content
		const content = getFirstBlobContent();
		expect(content).toBe(badInput);
	});

	it('triggers a download call via downloadDataUrl', () => {
		exportAsCalm(JSON.stringify(createMinimalArch(), null, 2));
		expect(downloadDataUrl).toHaveBeenCalled();
	});

	it('uses the provided filename in the download call', () => {
		exportAsCalm(JSON.stringify(createMinimalArch(), null, 2), 'my-arch.calm.json');
		expect(downloadDataUrl).toHaveBeenCalledWith(expect.any(String), 'my-arch.calm.json');
	});
});

// ─── exportAsScalerToml ───────────────────────────────────────────────────────

describe('exportAsScalerToml', () => {
	it('calls downloadDataUrl with default scaler.toml filename', () => {
		const arch = createMinimalArch();
		exportAsScalerToml(arch);
		expect(downloadDataUrl).toHaveBeenCalledWith(expect.any(String), 'scaler.toml');
	});

	it('calls buildScalerToml with the architecture object', () => {
		const arch = createMinimalArch();
		exportAsScalerToml(arch);
		expect(buildScalerToml).toHaveBeenCalledWith(arch);
	});

	it('uses custom filename when provided', () => {
		const arch = createMinimalArch();
		exportAsScalerToml(arch, 'my-cluster.toml');
		expect(downloadDataUrl).toHaveBeenCalledWith(expect.any(String), 'my-cluster.toml');
	});
});
