// SPDX-FileCopyrightText: 2026 CalmStudio Contributors
//
// SPDX-License-Identifier: Apache-2.0

/**
 * export.test.ts — Unit tests for export.ts CALM JSON transformation logic.
 *
 * Tests focus on:
 * - AIGF decorator injection (via exportAsCalm JSON transformation)
 * - _template metadata stripping
 * - Content preservation (nodes, relationships, controls)
 *
 * SVG/PNG export requires a real browser (html-to-image) and is skipped here.
 *
 * Strategy: Mock downloadDataUrl from $lib/io/fileSystem to capture content
 * and URL.createObjectURL/revokeObjectURL to prevent DOM navigation.
 */

import { describe, it, expect, beforeEach, vi, afterEach } from 'vitest';
import { createMinimalArch, createAIGovernanceArch } from '@calmstudio/calm-core/test-fixtures';

// ─── Mock fileSystem module to capture exported content ───────────────────────
// We intercept downloadDataUrl calls and capture the href (blob: URL) value.
// Since we also stub URL, we can recover the blob content from the href.

vi.mock('$lib/io/fileSystem', () => ({
	downloadDataUrl: vi.fn(),
}));

// Mock scalerToml module before importing export
vi.mock('$lib/io/scalerToml', () => ({
	buildScalerToml: vi.fn(function () { return '# Generated by CalmStudio\n[scheduler]\nscheduler_address = "tcp://127.0.0.1:8516"\n'; }),
}));

// Import export functions AFTER mocking their dependency
import { exportAsCalm, exportAsScalerToml, finalizeCalmForWrite, buildDecoratorSidecar, buildDesignZipEntries, exportDesignAsZip, designZipNameFor } from '$lib/io/export';
import { downloadDataUrl } from '$lib/io/fileSystem';
import { buildScalerToml } from '$lib/io/scalerToml';

// ─── Blob text capture helper ─────────────────────────────────────────────────

// Keep a registry of blob URL -> content for our fake Blob/URL
const blobRegistry = new Map<string, string>();
let blobCounter = 0;

function setupBlobStubs() {
	blobCounter = 0;
	blobRegistry.clear();

	// Stub Blob to store content in registry
	vi.stubGlobal(
		'Blob',
		class MockBlob {
			_id: string;
			constructor(parts: BlobPart[], _init?: BlobPropertyBag) {
				blobCounter++;
				this._id = `blob-${blobCounter}`;
				blobRegistry.set(this._id, (parts as string[]).join(''));
			}
		}
	);

	// Stub URL.createObjectURL to return a trackable fake URL
	vi.stubGlobal('URL', {
		createObjectURL: (blob: { _id: string }) => `blob:fake/${blob._id}`,
		revokeObjectURL: vi.fn(),
	});
}

function teardownBlobStubs() {
	vi.restoreAllMocks();
	vi.unstubAllGlobals();
	blobRegistry.clear();
}

/** Get the content of the first Blob created (the main CALM JSON export). */
function getFirstBlobContent(): string | null {
	return blobRegistry.get('blob-1') ?? null;
}

/** Get the content of the Nth Blob created (1-based). Sidecars follow the main file. */
function getBlobContent(n: number): string | null {
	return blobRegistry.get(`blob-${n}`) ?? null;
}

// ─── Setup / teardown ─────────────────────────────────────────────────────────

beforeEach(() => {
	vi.useFakeTimers();
	vi.clearAllMocks();
	setupBlobStubs();
});

afterEach(() => {
	vi.runAllTimers(); // flush all pending setTimeout callbacks before teardown
	vi.useRealTimers();
	teardownBlobStubs();
});

// ─── finalizeCalmForWrite (shared by Save / Save As / Export) ────────────────

describe('finalizeCalmForWrite', () => {
	const SCHEMA_URL = 'https://calm.finos.org/release/1.2/meta/calm.json';

	it('injects the canonical $schema when absent', () => {
		const result = JSON.parse(finalizeCalmForWrite(JSON.stringify(createMinimalArch())));
		expect(result['$schema']).toBe(SCHEMA_URL);
	});

	it('preserves an existing $schema untouched', () => {
		const arch = { '$schema': 'https://example.com/custom/schema.json', ...createMinimalArch() };
		const result = JSON.parse(finalizeCalmForWrite(JSON.stringify(arch)));
		expect(result['$schema']).toBe('https://example.com/custom/schema.json');
	});

	it('strips _template scratch metadata', () => {
		const arch = { ...createMinimalArch(), _template: { id: 'x', name: 'x' } };
		const result = JSON.parse(finalizeCalmForWrite(JSON.stringify(arch)));
		expect(result).not.toHaveProperty('_template');
	});

	it('strips embedded decorators (they belong in the sidecar)', () => {
		const arch = {
			...createMinimalArch(),
			decorators: [
				{ 'unique-id': 'd1', type: 'threat-model', target: ['architecture.json'], 'applies-to': ['api-service'], data: { x: 1 } },
			],
		};
		const result = JSON.parse(finalizeCalmForWrite(JSON.stringify(arch)));
		expect(result).not.toHaveProperty('decorators');
		// the rest of the document is untouched
		expect(result.nodes).toHaveLength(2);
	});

	it('does NOT add a governance decorator', () => {
		const result = JSON.parse(finalizeCalmForWrite(JSON.stringify(createAIGovernanceArch())));
		expect(result.decorators).toBeUndefined();
	});

	it('returns the input unchanged for malformed JSON', () => {
		expect(finalizeCalmForWrite('not-json')).toBe('not-json');
	});
});

// ─── exportAsCalm — _template metadata stripping ─────────────────────────────

describe('exportAsCalm — template stripping', () => {
	it('strips _template metadata from the output JSON', () => {
		const archWithTemplate = {
			...createMinimalArch(),
			_template: {
				id: 'test-template',
				name: 'Test',
				description: 'A test template',
				category: 'test',
				tags: [],
				version: '1.0',
				author: 'test',
			},
		};
		const json = JSON.stringify(archWithTemplate, null, 2);
		exportAsCalm(json);
		const content = getFirstBlobContent();
		expect(content).not.toBeNull();
		const result = JSON.parse(content!);
		expect(result).not.toHaveProperty('_template');
	});

	it('preserves nodes when _template is stripped', () => {
		const archWithTemplate = {
			...createMinimalArch(),
			_template: { id: 'x', name: 'x', description: '', category: 'x', tags: [], version: '1', author: 'x' },
		};
		exportAsCalm(JSON.stringify(archWithTemplate, null, 2));
		const result = JSON.parse(getFirstBlobContent()!);
		expect(result.nodes).toHaveLength(2); // createMinimalArch has 2 nodes
	});

	it('passes through clean arch without _template unchanged in structure', () => {
		exportAsCalm(JSON.stringify(createMinimalArch(), null, 2));
		const result = JSON.parse(getFirstBlobContent()!);
		expect(result.nodes).toHaveLength(2);
		expect(result.relationships).toHaveLength(1);
	});
});

// ─── exportAsCalm — no governance overlay (legacy AIGF retired) ───────────────

describe('exportAsCalm — no governance overlay', () => {
	it('does not inject a governance decorator for AI architectures', () => {
		exportAsCalm(JSON.stringify(createAIGovernanceArch(), null, 2));
		const result = JSON.parse(getFirstBlobContent()!);
		expect(result.decorators).toBeUndefined();
	});

	it('moves the author’s decorators out of the clean file into a sidecar', () => {
		const arch = createAIGovernanceArch({
			decorators: [
				{ 'unique-id': 'threat-model-overlay', type: 'threat-model', target: [], 'applies-to': ['ai-llm'], data: { sev: 'high' } },
			],
		});
		exportAsCalm(JSON.stringify(arch, null, 2), 'gov.calm.json');
		// Clean arch file (blob-1) carries no decorators…
		const main = JSON.parse(getFirstBlobContent()!);
		expect(main.decorators).toBeUndefined();
		// …they ride in the decorator sidecar (blob-2), target stamped to the arch file.
		const sidecar = JSON.parse(getBlobContent(2)!);
		expect(sidecar.decorators).toHaveLength(1);
		expect(sidecar.decorators[0]['unique-id']).toBe('threat-model-overlay');
		expect(sidecar.decorators[0].target).toEqual(['gov.calm.json']);
		// the sidecar download is deferred via setTimeout — flush before asserting
		vi.runAllTimers();
		expect(downloadDataUrl).toHaveBeenCalledWith(expect.any(String), 'gov.calm.decorators.json');
	});

	it('writes no decorator sidecar when there are none', () => {
		exportAsCalm(JSON.stringify(createMinimalArch(), null, 2), 'plain.calm.json');
		vi.runAllTimers();
		expect(downloadDataUrl).not.toHaveBeenCalledWith(expect.any(String), 'plain.calm.decorators.json');
	});
});

// ─── buildDecoratorSidecar ────────────────────────────────────────────────────

describe('buildDecoratorSidecar', () => {
	it('returns null when the architecture has no decorators', () => {
		expect(buildDecoratorSidecar(JSON.stringify(createMinimalArch()), 'a.json')).toBeNull();
	});

	it('returns null for malformed JSON', () => {
		expect(buildDecoratorSidecar('not-json', 'a.json')).toBeNull();
	});

	it('wraps decorators and stamps target to the arch filename', () => {
		const arch = {
			...createMinimalArch(),
			decorators: [
				{ 'unique-id': 'd1', type: 'gemara-link', target: ['architecture.json'], 'applies-to': ['api-service'], data: { k: 1 } },
			],
		};
		const sidecar = JSON.parse(buildDecoratorSidecar(JSON.stringify(arch), 'payments.arch.json')!);
		expect(sidecar.decorators[0].target).toEqual(['payments.arch.json']);
		// placeholder 'architecture.json' replaced, not appended
		expect(sidecar.decorators[0].target).not.toContain('architecture.json');
	});

	it('preserves additional explicit (non-placeholder) targets', () => {
		const arch = {
			...createMinimalArch(),
			decorators: [
				{ 'unique-id': 'd1', type: 'gemara-link', target: ['other.arch.json'], 'applies-to': ['api-service'], data: { k: 1 } },
			],
		};
		const sidecar = JSON.parse(buildDecoratorSidecar(JSON.stringify(arch), 'payments.arch.json')!);
		expect(sidecar.decorators[0].target).toEqual(['payments.arch.json', 'other.arch.json']);
	});
});

// ─── exportAsCalm — content preservation ─────────────────────────────────────

describe('exportAsCalm — CALM field preservation', () => {
	it('preserves all nodes in output', () => {
		const arch = createMinimalArch();
		exportAsCalm(JSON.stringify(arch, null, 2));
		const result = JSON.parse(getFirstBlobContent()!);
		expect(result.nodes).toHaveLength(arch.nodes.length);
		expect(result.nodes[0]['unique-id']).toBe('api-service');
	});

	it('preserves all relationships in output', () => {
		const arch = createMinimalArch();
		exportAsCalm(JSON.stringify(arch, null, 2));
		const result = JSON.parse(getFirstBlobContent()!);
		expect(result.relationships).toHaveLength(arch.relationships.length);
		expect(result.relationships[0]['unique-id']).toBe('api-to-db');
	});

	it('preserves node controls in AI arch output', () => {
		exportAsCalm(JSON.stringify(createAIGovernanceArch(), null, 2));
		const result = JSON.parse(getFirstBlobContent()!);
		const llmNode = result.nodes.find((n: { 'unique-id': string }) => n['unique-id'] === 'ai-llm');
		expect(llmNode).toBeDefined();
		expect(llmNode.controls['security-domain']).toBeDefined();
	});

	it('outputs original content for malformed input (graceful fallback)', () => {
		const badInput = 'not-valid-json';
		exportAsCalm(badInput);
		// With invalid JSON, falls through to Blob with original content
		const content = getFirstBlobContent();
		expect(content).toBe(badInput);
	});

	it('triggers a download call via downloadDataUrl', () => {
		exportAsCalm(JSON.stringify(createMinimalArch(), null, 2));
		expect(downloadDataUrl).toHaveBeenCalled();
	});

	it('uses the provided filename in the download call', () => {
		exportAsCalm(JSON.stringify(createMinimalArch(), null, 2), 'my-arch.calm.json');
		expect(downloadDataUrl).toHaveBeenCalledWith(expect.any(String), 'my-arch.calm.json');
	});
});

// ─── Design zip export ────────────────────────────────────────────────────────

describe('buildDesignZipEntries', () => {
	it('bundles the clean arch (no decorators) and the decorator sidecar', () => {
		const arch = {
			...createMinimalArch(),
			decorators: [
				{ 'unique-id': 'd1', type: 'threat-model', target: ['architecture.json'], 'applies-to': ['api-service'], data: { x: 1 } },
			],
		};
		const entries = buildDesignZipEntries(JSON.stringify(arch), 'payments.arch.json');
		const byName = Object.fromEntries(entries.map((e) => [e.name, e.content]));

		// arch entry is decorator-free
		expect(JSON.parse(byName['payments.arch.json']).decorators).toBeUndefined();
		// decorator sidecar present, target stamped to the arch file
		const sidecar = JSON.parse(byName['payments.arch.decorators.json']);
		expect(sidecar.decorators[0].target).toEqual(['payments.arch.json']);
	});

	it('omits the decorator sidecar entry when there are none', () => {
		const entries = buildDesignZipEntries(JSON.stringify(createMinimalArch()), 'plain.arch.json');
		expect(entries.map((e) => e.name)).toEqual(['plain.arch.json']);
	});

	it('preserves layout in the arch entry when supplied', () => {
		const entries = buildDesignZipEntries(JSON.stringify(createMinimalArch()), 'a.json', 'My Design', {
			'api-service': { x: 10, y: 20 },
		});
		const arch = JSON.parse(entries[0].content);
		expect(arch.metadata.name).toBe('My Design');
		expect(arch.metadata['calmstudio-layout']['api-service']).toEqual({ x: 10, y: 20 });
	});
});

describe('designZipNameFor', () => {
	it('replaces the trailing .json with .zip', () => {
		expect(designZipNameFor('payments.arch.json')).toBe('payments.arch.zip');
	});
});

describe('exportDesignAsZip', () => {
	it('triggers a .zip download', () => {
		exportDesignAsZip(JSON.stringify(createMinimalArch()), 'payments.arch.json');
		expect(downloadDataUrl).toHaveBeenCalledWith(expect.any(String), 'payments.arch.zip');
	});
});

// ─── exportAsScalerToml ───────────────────────────────────────────────────────

describe('exportAsScalerToml', () => {
	it('calls downloadDataUrl with default scaler.toml filename', () => {
		const arch = createMinimalArch();
		exportAsScalerToml(arch);
		expect(downloadDataUrl).toHaveBeenCalledWith(expect.any(String), 'scaler.toml');
	});

	it('calls buildScalerToml with the architecture object', () => {
		const arch = createMinimalArch();
		exportAsScalerToml(arch);
		expect(buildScalerToml).toHaveBeenCalledWith(arch);
	});

	it('uses custom filename when provided', () => {
		const arch = createMinimalArch();
		exportAsScalerToml(arch, 'my-cluster.toml');
		expect(downloadDataUrl).toHaveBeenCalledWith(expect.any(String), 'my-cluster.toml');
	});
});
