apiVersion: apps/v1
kind: Deployment
metadata:
  name: calmhub
  labels:
    app: calmhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calmhub
  template:
    metadata:
      labels:
        app: calmhub
    spec:
      containers:
        - name: calmhub
          image: jpgough/calm-hub:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: calmhub
  labels:
    app: calmhub
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: calmhub
