name: Build Shared

permissions:
    contents: read

on:
    pull_request:
        branches:
            - 'main'
            - 'release*'
    push:
        branches:
            - 'main'
            - 'release*'

jobs:
    shared:
        name: Build, Test, and Lint Shared Module
        runs-on: ubuntu-latest

        steps:
            - name: Checkout PR Branch
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

            - name: Setup Node.js
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
              with:
                  node-version: v22

            - name: Install workspace
              run: npm ci

            - name: Lint Shared Module
              run: npm run lint --workspace=shared

            - name: Build workspace
              run: npm run build:shared

            - name: Run tests with coverage for Shared
              run: npm run test --workspace=shared
