name: Build CALM Visualizer

permissions:
    contents: read

on:
    pull_request:
        branches:
            - 'main'
    push:
        branches:
            - 'main'

jobs:
    calm-visualizer:
        name: Build, Test, and Lint CALM Visualizer
        runs-on: ubuntu-latest

        steps:
            - name: Checkout PR Branch
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

            - name: Setup Node.js
              uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
              with:
                  node-version: v22

            - name: Install workspace
              run: npm ci

            - name: Lint Module
              run: npm run lint --workspace=calm-visualizer

            - name: Build workspace
              run: npm run build --workspace=calm-visualizer

            - name: Run tests
              run: npm run test:run --workspace=calm-visualizer
