name: Build Translators

on:
  push:
    branches: ["main"]
    paths: ["translator/**"]
  pull_request:
    branches: ["main"]
    paths: ["translator/**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      - run: mvn -B install --file ./translator/pom.xml
