name: Publish Major Release

permissions:
  contents: write
  id-token: write

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.event.release.tag_name, 'v') && !github.event.release.prerelease
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22

      - run: npm ci
      - run: npm run build

      - name: Update version and publish
        run: |
          VERSION=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          echo "Publishing version: $VERSION"
          
          cd cli
          npm version $VERSION --no-git-tag-version
          
          # Update changelog
          if [ ! -f CHANGELOG.md ]; then
            echo "# Changelog" > CHANGELOG.md
            echo "" >> CHANGELOG.md
          fi
          
          echo "## [$VERSION] - $(date +%Y-%m-%d)" > temp_changelog.md
          echo "" >> temp_changelog.md
          echo "${{ github.event.release.body }}" >> temp_changelog.md
          echo "" >> temp_changelog.md
          cat CHANGELOG.md >> temp_changelog.md
          mv temp_changelog.md CHANGELOG.md

      - name: Commit and publish
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cli/package.json cli/CHANGELOG.md
          git commit -m "chore(cli): release ${{ github.event.release.tag_name }} [skip ci]" || true
          git push origin HEAD:main
          
          cd cli
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
