name: Validation of CALM Samples

on:
  pull_request:
    branches: 
      - "main"
    paths: 
      - "calm/draft/**"
      - "calm/pattern/**"
      - "calm/samples/**"
      - "spectral/**" 
  push:
    branches: 
      - "main"
    paths: 
      - "calm/draft/**"
      - "calm/pattern/**"
      - "calm/samples/**"
      - "spectral/**" 

jobs:
  spectrals:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Run Spectral
      - uses: actions/setup-node@v4
        with:
          node-version: v20
      - run: npm install @stoplight/spectral-cli
      - run: npx spectral lint --ruleset spectral/instantiation/validation-rules.yaml 'calm/samples/api-gateway-instantiation(*.json|*.yaml)'

